apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "config.polyglot.systems/v1",
          "kind": "CertificateSentinel",
          "metadata": {
            "name": "certificatesentinel-sample"
          },
          "spec": {
            "alert": {
              "config": {
                "reportInterval": "debug"
              },
              "name": "secrets-logger",
              "type": "logger"
            },
            "logLevel": 2,
            "scanningInterval": 60,
            "target": {
              "apiVersion": "v1",
              "daysOut": [
                30,
                60,
                90,
                9001,
                9000
              ],
              "kind": "Secret",
              "name": "all-secrets",
              "namespaces": [
                "*"
              ],
              "serviceAccount": "some-service-account"
            }
          }
        },
        {
          "apiVersion": "config.polyglot.systems/v1",
          "kind": "KeystoreSentinel",
          "metadata": {
            "name": "keystoresentinel-sample"
          },
          "spec": {
            "alert": {
              "config": {
                "reportInterval": "debug"
              },
              "name": "secrets-logger",
              "type": "logger"
            },
            "logLevel": 2,
            "scanningInterval": 60,
            "target": {
              "apiVersion": "v1",
              "daysOut": [
                30,
                60,
                90,
                9001,
                9000
              ],
              "keystorePassword": {
                "plaintext": "changeit",
                "type": "plaintext"
              },
              "kind": "Secret",
              "name": "all-secrets",
              "namespaces": [
                "*"
              ],
              "serviceAccount": "some-service-account"
            }
          }
        }
      ]
    capabilities: Basic Install
    operators.operatorframework.io/builder: operator-sdk-v1.8.0-ocp
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  name: certificate-sentinel-operator.v0.0.2
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: CertificateSentinel scans Secrets and ConfigMaps for x509 Certificates
        that are expiring and reports on them
      displayName: Certificate Sentinel
      kind: CertificateSentinel
      name: certificatesentinels.config.polyglot.systems
      version: v1
    - description: KeystoreSentinel scans Secrets and ConfigMaps for Java Keystores
        with certificates that are expiring and reports on them
      displayName: Keystore Sentinel
      kind: KeystoreSentinel
      name: keystoresentinels.config.polyglot.systems
      version: v1
  description: Scan and report on x509 Certificates and Java Keystores that will soon
    expire
  displayName: Certificate Sentinel
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAADIAAAAyCAYAAAAeP4ixAAAABmJLR0QA/wD/AP+gvaeTAAANJ0lEQVRoge2ae1jVVbrHP/u+ucj9jjAiKuQdNYGDt2xM1ENZmaNWY02mNZpOU57qZKdJJrWTqdmjxyknM2sap5qj4ziTaaLMRkkFRC5HREEFBTcgN4G92Zc1f6wNbrabi9o5z/mj7/P8HmCt32+973etd73vu94F/Igf8b8CxV18qwbGAmOAOMDL0dYCXABOA9lAWy/j+AONgP0udOkRoYDWTXs88DugHhC9PG3An4CJ3ciIBdqBtd30ewCDAFVvyna3IlFAGfAhsNTRFgH8BngaOfPED+5P8th4wkL9CQ70QaNRU22sp/Z6E7n5F8g5cwG7vXOi/wq8ChQ5yfEHPga2A/tddFgKrAf0QBUwHzh6u0S8gG3AbocCMxXwRwH9PD114ul5P1XMnpFEZHhgd+MCUN94gwOHc9n26TcYaxoArMBLwOYeP5TmelKtUChHeHqS19KCAmoEDABab4eIM14C3gFUcx+cwPJn0wjw7wfA2dJKMrLOcLHCiLGmAavNTkiQL5FhgUxKHk7CyIGolEpMpnZ27j7Mlh37sVptAB8hZ9zSjcwXgQ2vRkayNjqaacXFHGpsBEgETvRBZ7cDCo1aJd5+7UlRbNgqiv6xRWxMXyRiokN72x8iMMBHvLbiMZGfsVkUG7aKz/7rJRHg18/u6N/Zg9w5gBjl5SW2xMQIf7XaDtiQ5u0WPa3IdGC/Rq1SfvjeMkXi2Diu1zfz4hvbOXm6FIChQwaQNj2FexPiiQgLRq1SUWWso6D4AvsPHic7pwghBD/pH8LmNYsZPDCCiis1LHhuPXX1zSBXe4Mb2WrgCJDi1LYeWHm7RIKBUsB39SuPMycthQsXq1jy8hauVl9nSGwU6a8uYsb9ST3MA+SeOcfraz4k60QBXp56NqYvYkLiUHILLvD08veFxWK1A8nASTefa4HHgcGAAfhbT7K6c2trgcmzZyTxwqI0LlXW8Pjz71FT18jggVE89uAUGhpvkH2q6JbHZDITEx1OftF5jLX1/MfLT6FQwGFDLgeP5jEhaRijhsbg6aFTZJ0oVjoUdWdmNmQs+s4xqbeNgYBZr9PaM/57jSg2bBVRkcG97oeOx8/XWzSVHRCjhg8SOq1GNJz/RjSVHRArl84XgIgMDxS5hzaJ/IzNzuPOuhNFnaF207YU0C54dDKhwX4cOVZAxZUaAvx9eP6p2Wg1mh4HHD1iMAAb3lpGfWMzSqW03tdfXEhuQSnfZZ5i5+7DLFmYyguL/pV/e2sHSKfiGkduC657RAFUAhF7dq5iSGwEjz2zjqKSy3zywes8MmsSVpuNvx3K5mTe/6DXaZmSkkDK+BF9Ena29DLJM5fgoddydO86FAoFKbNW0mZqtyM90rU7JaJ0+TseiIiKCGJIbAQVV2spKrnMT6LCeHjmRKqN15kyezlPPL+a9z/8knc++JwZ817myV+mY27vLiQ4DT44mtSpidxoMZF1ohi9TsOExKEdeky5UxLuiCQA3JswBIDMY4UAzJqWDMDCZW9zpug84VEDeHjhEmb+7Of4+Pmz9xsDb/7n7/skMO0B6VGPZMmxxztkIaN5b5gIvAvcYt+ue2QgQFiIHwAXK40AjBsVR05+CcdPFRIYEsby1evR6vQAjE6ayLuvLGX7Z3/lodQJeOh1tLdbaDOZ8fXxpqXVhNVqxdfHm5jocMaOigPgkmPsUIesDtm9YDGwAJniVPRExBcgJMgXgJraRiSxQIpKygEYNjaxkwRAYGg4nl79aKyvY/rcl3rUYtzoePbsXAOA0TF2SFAnET/3X3XBUmCdKwm41bS6jfS+Pt4ANNTVdmkXQmAXAoCkscO4LyUBTw8dABPGj0ClVKJSKrkvJYH5j/wUtUqGLpvNBoBK1amCrQ9EmuiaPXdLpBGgpq4JgGDHylQb65icPBovTw8KTh7jZOZ3DmWs7P/iE5obrjM8PoZvv9zA3l3rSBw7DH+/fvx55xq0Og1anYa9u9bx7BNpXKutB8DPx0sKbGrpkH29D0S6hatplQFckyk30ZHBAOSeKWVO2n2seX0xv1q1mT9u28hfPtuO1WKh3WxCp9Oy8bfLOwfZ/dFbtLdb0Ou0xESFo1DcXOic/BIA4gZFAnCpsqaj68rdEHFdkdMAJ/NkRjA5eTgA+w8eQwjB0/Nn8odtbzJyaCytN5qxWdu5LyWBQ19uJHHM0M5B9DotPv3kjB/Z+wEZe24eP/YdyAJuesbThWUdXdl3Q8R1RYqBqkuVxvDz5VUMigknblB/Ss5Xsu/bYzw4PYVZ05KZNS2ZNpMZtVqFRu0uObgJve7maflSRTX7Dx7DQ69j2uTRWCxWDN8XgzyvZ90NEXfYBIjFT04XxYat4oO1SwQgBsX0F9WFe0VT2QHx1cfpIiTIX/j5et/Wo9GoBSCemne/KDZsFZvSn+3ItQ646JAI5AGj+qq0q2kBbAEsu77MEDV1jdw/cRTjE4ZwvryS51auRwiByWzBauuLk7kJs9mCxWJFrVbxzIIHsNsF2z79e0f3dpfXw4DhQFBfx+/O3W4BfjknLYXVrzxO7fUm5i56h2pjPXPSprDlnV/jodf1SYDNZmf91i9Ys2kXarWKHe+vYMzIWN7euJvPvz4KUIiceddykBp5xneFHjC5NnZ3HslRwJLicxW6/hFBjBkRS9K4eDIMZzh5uoS/H8omdkAEMdHhPZI4W3qZny9N5w9fH0SrUbNh9TOkjL+HwrOXeGv9FwgZf6zIklGTy+euxLyAr4BPgGeRjuliR2dPR900YI9Go1bseH+FYszIWIy1jfxq1UedniZhxBAeTE0hccxQwkIC8PDQU1vbwKn8Enbv+Y7sHBm7IsICWP+bXzB6+ECqjfXMW/wuxtoGPL08aW1pBel6C4DPgc+60ecNYLWPSkWTNOsqIBK5x26BB11X6VVAaDRqsXbVQlFs2CoKM7eIdW8sFJHhgb0esnx9vMRzC2eInEObRLFhq/j649dEWLCfHRDBIcFi8tRJwt/fz/W73+EmKQQ+BUR6VJQIUqs73vXt6HReEW/kUh0C5jm1rwJWKxQoFjw6hWW/mIWvjxd2u6Dw7CUyss5QdrGa2utNtJna8fPxIjYmnMQxQ5iQOAy9ToPNZid9w26+2peF3W4nNCyE+KHxmM1m8nJOYzaZ8fT0xGKxYLFYADKAuYBzPvQo0rQ6kAFMdUdEg7RVA/Cey2w8rFCwSwi8fPp5suiJB3goNZHgQF96QpupnQMZuWz//FvKLlYDoNVqGZ98LzabjbxTpzGZTERERDBp0iRaWlrIzMykUdawKoFH6FqY+BmyVFSGTB7r3RHpDdFAOvAEoFQqFIwYOoCkcXGEh/gTHOSHTqumobGFyqu15BeVcyKvlJbWTgfzPbIykuDp5YnNasNsNhMVFUVKSgpKpYwEFouF7OxsKioqAMzI1P3T3pTrC5HxSFv8B9LtjQJ+jZwt716+tQD7kHHiG8f7R3AcolxJdEAIQUFBAYWFhSD3wrvAv9NDhtwbke3AM47fC4F/AZodf+uAJGAcEIOshdmBOqRH+d7xNNMVO4Cn9Ho9s2fPvoWEMyoqKjh+/LiwWq0KZPSfj5M59ZVIHHA2WKOhv1ZLXksLwDJksLwbTAYOKZVK1dSpUxUhISE9vtzQ0EBmZiY3btwAOA/Mxs2ZpPvpkDOOp1KJ/83EsG/hvGccBVba7XaFwWAQra1ui+ud8PPzIzU1lfDwcJB3Jdl0LaUCPV+gGIF7G222weVmMwq4ijxqtvTwTV+RDcRardZRRqORmJgYtybW3t5OU1MTer2egQMHYrVaqa2t1QIPI6uTN/pCBKQ7zge+BVbQ1a/fLh4CHkPeUFUiN39qW1tbRGtrK1FRUV1ePnfuHIcPH6a0tJTS0lJ8fX2Ji4ujtbWV+vp6D2Tw7qwH92RaIPOgPyNvle7mKLoa2IN031lIj9fm+FlTXl5OSUlJ58sNDQ3k5OQA4Ovni8Vi4fjx47S3tzNy5MiOE+dcZwG9Efmh8LxKoWCFtHMl8Jyj/bJDIUtubi7XrslCY01NDUII+kf3Z8y4BAKDArFYLNTX1+Ph4YG3tzdIL9l5ZfZ/RaTRJgRZzZ2euNGp7wjwshACg8EgWlpaOhTFeM3IxbKLNDTIGkJHu9O9ZGd509n9KoHfAjnAX5BpStgdKl6BvJTpkJimgN0CPBRQJWAat7rQT4CFAQEBTJs2jaysLCorKzs777nnHhISEmhubmbfvn0A5TgV9ZyJ+CCLyBnAC8A57nzFTMjrbeczRiDSfRbi3vPpkdnDuAEDBpCUlMSVK1doamoiKCiI0NBQhBAcPXqUq1evgtx3b7ojAjKfanAoMAinNPk2UYO0/9tFFDJJDI2MjCQhIQEfHx9AOoC8vDyqqqpABsZxOJno3fzngzMeQuZCvV7s9wF65C2WFuiML077wowkchZ53HB3HL5jvEcfb7R+wKcOp6T1h1oRJdIsfogVcUVHfuQ68zXcmpD+iP83+CcbKBy3W67peQAAAABJRU5ErkJggg==
    mediatype: image/png
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - config.polyglot.systems
          resources:
          - certificatesentinels
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - config.polyglot.systems
          resources:
          - certificatesentinels/finalizers
          verbs:
          - update
        - apiGroups:
          - config.polyglot.systems
          resources:
          - certificatesentinels/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - config.polyglot.systems
          resources:
          - keystoresentinels
          verbs:
          - create
          - delete
          - get
          - list
          - patch
          - update
          - watch
        - apiGroups:
          - config.polyglot.systems
          resources:
          - keystoresentinels/finalizers
          verbs:
          - update
        - apiGroups:
          - config.polyglot.systems
          resources:
          - keystoresentinels/status
          verbs:
          - get
          - patch
          - update
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - secrets
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - get
          - list
          - watch
        - apiGroups:
          - authentication.k8s.io
          resources:
          - tokenreviews
          verbs:
          - create
        - apiGroups:
          - authorization.k8s.io
          resources:
          - subjectaccessreviews
          verbs:
          - create
        serviceAccountName: certificate-sentinel-operator-controller-manager
      deployments:
      - name: certificate-sentinel-operator-controller-manager
        spec:
          replicas: 1
          selector:
            matchLabels:
              control-plane: controller-manager
          strategy: {}
          template:
            metadata:
              labels:
                control-plane: controller-manager
            spec:
              containers:
              - args:
                - --secure-listen-address=0.0.0.0:8443
                - --upstream=http://127.0.0.1:8080/
                - --logtostderr=true
                - --v=10
                image: registry.redhat.io/openshift4/ose-kube-rbac-proxy:v4.8
                name: kube-rbac-proxy
                ports:
                - containerPort: 8443
                  name: https
                resources: {}
              - args:
                - --health-probe-bind-address=:8081
                - --metrics-bind-address=127.0.0.1:8080
                - --leader-elect
                command:
                - /manager
                image: quay.io/polyglotsystems/certificate-sentinel-operator:v0.0.2
                livenessProbe:
                  httpGet:
                    path: /healthz
                    port: 8081
                  initialDelaySeconds: 15
                  periodSeconds: 20
                name: manager
                readinessProbe:
                  httpGet:
                    path: /readyz
                    port: 8081
                  initialDelaySeconds: 5
                  periodSeconds: 10
                resources:
                  limits:
                    cpu: 200m
                    memory: 500Mi
                  requests:
                    cpu: 200m
                    memory: 500Mi
                securityContext:
                  allowPrivilegeEscalation: false
              securityContext:
                runAsNonRoot: true
              serviceAccountName: certificate-sentinel-operator-controller-manager
              terminationGracePeriodSeconds: 10
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - coordination.k8s.io
          resources:
          - leases
          verbs:
          - get
          - list
          - watch
          - create
          - update
          - patch
          - delete
        - apiGroups:
          - ""
          resources:
          - events
          verbs:
          - create
          - patch
        serviceAccountName: certificate-sentinel-operator-controller-manager
    strategy: deployment
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - ssl
  - x509
  - certificate
  - certificates
  - pem
  - tls
  - jks
  - java
  - keystore
  - scanning
  - reporting
  links:
  - name: Certificate Sentinel Operator
    url: https://github.com/PolyglotSystems/certificate-sentinel-operator/
  maintainers:
  - email: ken@kenmoini.com
    name: Ken Moini
  maturity: alpha
  provider:
    name: Polyglot Systems
    url: https://github.com/PolyglotSystems/certificate-sentinel-operator/
  version: 0.0.2
