# permissions for end users to view certificatesentinels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: certificatesentinel-viewer-role
rules:
- apiGroups:
  - config.polyglot.systems
  resources:
  - certificatesentinels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.polyglot.systems
  resources:
  - certificatesentinels/status
  verbs:
  - get
