# permissions for end users to view keystoresentinels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keystoresentinel-viewer-role
rules:
- apiGroups:
  - config.polyglot.systems
  resources:
  - keystoresentinels
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - config.polyglot.systems
  resources:
  - keystoresentinels/status
  verbs:
  - get
