# permissions for end users to edit keystoresentinels.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: keystoresentinel-editor-role
rules:
- apiGroups:
  - config.polyglot.systems
  resources:
  - keystoresentinels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - config.polyglot.systems
  resources:
  - keystoresentinels/status
  verbs:
  - get
