apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: certificate-sentinel-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: certificate-sentinel-operator
  source: polyglotsystems-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: certificate-sentinel-operator.v0.0.3