apiVersion: config.polyglot.systems/v1
kind: KeystoreSentinel
metadata:
  name: keystoresentinel-sample
spec:
  logLevel: 2
  scanningInterval: 60
  alert:
    name: secrets-logger
    type: logger
    config:
      reportInterval: debug
  target:
    apiVersion: v1
    daysOut:
      - 30
      - 60
      - 90
      - 9001
      - 9000
    kind: Secret
    name: all-secrets
    namespaces:
      - '*'
    serviceAccount: some-service-account
    keystorePassword:
      plaintext: changeit
      type: plaintext