apiVersion: config.polyglot.systems/v1
kind: CertificateSentinel
metadata:
  name: certificatesentinel-sample
spec:
  targets:
    - name: all-secrets
      namespaces:
      - "*"
      kind: Secret
      apiVersion: v1
      serviceAccount: some-service-account
  alerts:
    - name: secrets-logger
      type: logger
  scanningInterval: 60