apiVersion: config.polyglot.systems/v1
kind: CertificateSentinel
metadata:
  name: certificatesentinel-sample-secrets-mailer
  namespace: cert-sentinel
spec:
  alert:
    config:
      reportInterval: debug
      smtp_auth_secret: my-gmail-smtp-secret
      smtp_auth_type: plain
      smtp_destination_addresses:
        - ken@kenmoini.com
        - ken.moini@gmail.com
      smtp_endpoint: 'smtp.gmail.com:587'
      smtp_sender_hostname: core-ocp.kemo.labs
      smtp_use_ssl: true
      smtp_use_starttls: true
    name: secrets-mailer
    type: smtp
  target:
    apiVersion: v1
    daysOut:
      - 30
      - 60
      - 90
      - 9001
      - 9000
    kind: Secret
    name: all-secrets
    namespaces:
      - cert-sentinel
      - openshift-apiserver
      - openshift-kube-scheduler
    serviceAccount: some-service-account